name: Check URLs

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:
  
jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check URLs
      run: |
        docker run --rm -v $PWD:/input:ro lycheeverse/lychee /input/**/*.md --config /input/.github/lychee.yml