name: Check URLs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 8 * * 1'
  workflow_dispatch:
  
jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install lychee
      run: |
        cargo install lychee

    - name: Check URLs in Markdown files
      run: lychee ./**/*.md